// UserList = new Mongo.Collection('userlist'); // Not needed
Courts = new Mongo.Collection('Courts');
Addresses = new Mongo.Collection('Addresses');
Questions = new Mongo.Collection('Questions');
Pairs = new Mongo.Collection('Pairs');
Payments = new Mongo.Collection('Payments');
Matches = new Mongo.Collection('Matches');
Years = new Mongo.Collection('Years');
Types = new Mongo.Collection('Types');
Pools = new Mongo.Collection('Pools');
Extras = new Mongo.Collection('Extras');
ModificationsLog = new Mongo.Collection('ModificationsLog');
GlobalValues = new Mongo.Collection('GlobalValues');
Threads = new Mongo.Collection('Threads');
Topics = new Mongo.Collection('Topics');
